### ISSUE TITLE
Invalid email is valid if strict: true 

### ISSUE THREAD

**Issue by rud-felix** [egulias/EmailValidator#92]
Invalid email **email@gmail** is valid if **strict: true**
```
email:
    - Email:
        groups:  [user_register]
        message: Email {{ value }} is not valid
        strict: true
        checkMX: true
        checkHost: true
```
